#!/usr/bin/env bash
# Install nginx on web server;

apt update
apt install -y nginx

service nginx start

rm /var/www/html/index.nginx-debian.html

echo "<html><head></head><body><p>Holberton School</p></body></html>" > /var/www/html/index.html
service nginx restart

exit 0
