#!/usr/bin/env bash
# Install Nginx on web-01 server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx start
